---
- name: Post-install steps
  hosts: localhost
  become: true

  tasks:
    - name: Full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install required packages
      community.general.pacman:
        name:
          - stow
          - thefuck
          - wezterm
          - eza
          - fzf
          - zoxide
          - bluetui
          - impala
          - btop
          - nautilus
        state: present
